package main

// TYPES
type Mention string
type Group string
type Option string
type OptionGroup string

// CODE APOGEE FROM ametice.univ-amu.fr/pluginfile.php/9746522/mod_resource/content/6/%402025-08-29_-_M1_%3D_Liste_des_ECUE.pdf
const CODE_POC string = "SINA09D"
const CODE_SDD_AA string = "SINA10B"
const CODE_COMPLEXITE string = "SINA09B"
const CODE_BDD_AVANCE string = "SINA20A"
const CODE_PROBA_POUR_INFORMATIQUE string = "SINA12A"
const CODE_GENIE_LOG string = "SINA09E"
const CODE_CRYPTOGRAPHIE string = "SINA09F"
const CODE_PROG_CPP string = "SINA12B"
const CODE_DONNEES_POST_RELATIONNELLES string = "SINA20B"
const CODE_PROG_FONCTIONNELLE string = "SINA15A"
const CODE_RESEAUX string = "SINA09A"
const CODE_METHODE_NUM_INFORMATIQUE string = "SINA13A"
const CODE_SECURITE_DES_APPS string = "SINA10A"
const CODE_GESTION_PROJETS string = "SINA11B"

const CODE_ANALYSE_DES_DONNEES string = "SINB44B"
const CODE_ARCHITECTURES_JEE string = "SINB44D"
const CODE_ANGLAIS_DE_INFORMATIQUE string = "SINB35B"
const CODE_ALGORITHMES_A_PERFORMANCES_GARANTIES string = "SINB33B"
const CODE_ANALYSE_DE_PROGRAMMES string = "SINB33G"
const CODE_ALGORITHMIQUE_ET_RECHERCHE_OPERATIONNELLE string = "SINB33E"
const CODE_ALGORITHMES_ET_SYSTEMES_ROBUSTES string = "SINB33H"
const CODE_BASES_DE_APPRENTISSAGE_ARTIFICIEL string = "SINB37A"
const CODE_CALCULABILITE_AVANCEE string = "SINB40A"
const CODE_DES_CONTENEURS_AU_CLOUD string = "SINB34B"
const CODE_COMMUNICATION_SCIENTIFIQUE_ET_PROFESSIONNELLE string = "SINB33F"
const CODE_EXPLORATION_DES_DONNEES string = "SINB49A"
const CODE_FIABILITE_LOGICIELLE string = "SINB34A"
const CODE_GENIE_LOGICIEL_AVANCE string = "SINBU33DL"
const CODE_INTEGRATION_DES_DONNEES string = "SINB44A"
const CODE_INTERFACE_HUMAIN_MACHINE string = "SINB38B"
const CODE_INFORMATIQUE_QUANTIQUE string = "SINB33A"
const CODE_MODELISATION_GEOMETRIQUE_ET_MAILLAGES string = "SINB37D"
const CODE_MODELISATION_ET_RESOLUTION_POUR_LA_DECISION string = "SINB41A"
const CODE_PROGRAMMATION_GRAPHIQUE string = "SINB38A"
const CODE_RESEAUX_DE_NEURONES string = "SINB46A"
const CODE_SURFACES_DE_FORME_LIBRE string = "SINB37C"
const CODE_TRAITEMENT_AUTOMATIQUE_DES_LANGUES string = "SINB44C"
const CODE_THEORIE_DE_LA_COMPLEXITE string = "SINB33C"
const CODE_TRAVAUX_ETUDE_ET_RECHERCHE string = "SINB35A"
const CODE_THEORIE_STRUCTURELLE_DES_GRAPHES string = "SINB37B"
const CODE_REU_GIG string = "Réunion pour les étudiants du parcours GIG"

// Lists of every course each mention do not have to follow
var mentionToCodesMap = map[string][]string{
	"IDL": {CODE_REU_GIG, CODE_THEORIE_DE_LA_COMPLEXITE, CODE_THEORIE_STRUCTURELLE_DES_GRAPHES, CODE_RESEAUX_DE_NEURONES, CODE_TRAITEMENT_AUTOMATIQUE_DES_LANGUES, CODE_MODELISATION_ET_RESOLUTION_POUR_LA_DECISION, CODE_PROGRAMMATION_GRAPHIQUE, CODE_SURFACES_DE_FORME_LIBRE, CODE_INTERFACE_HUMAIN_MACHINE, CODE_MODELISATION_GEOMETRIQUE_ET_MAILLAGES, CODE_INFORMATIQUE_QUANTIQUE, CODE_INTEGRATION_DES_DONNEES, CODE_EXPLORATION_DES_DONNEES, CODE_CALCULABILITE_AVANCEE, CODE_BASES_DE_APPRENTISSAGE_ARTIFICIEL, CODE_ANALYSE_DE_PROGRAMMES, CODE_ALGORITHMES_ET_SYSTEMES_ROBUSTES, CODE_ALGORITHMES_A_PERFORMANCES_GARANTIES, CODE_ANALYSE_DES_DONNEES, CODE_METHODE_NUM_INFORMATIQUE, CODE_SDD_AA, CODE_PROBA_POUR_INFORMATIQUE, CODE_CRYPTOGRAPHIE, CODE_PROG_CPP, CODE_PROG_FONCTIONNELLE, CODE_METHODE_NUM_INFORMATIQUE},
	"I3A": {CODE_REU_GIG, CODE_THEORIE_DE_LA_COMPLEXITE, CODE_THEORIE_STRUCTURELLE_DES_GRAPHES, CODE_INTERFACE_HUMAIN_MACHINE, CODE_PROGRAMMATION_GRAPHIQUE, CODE_SURFACES_DE_FORME_LIBRE, CODE_MODELISATION_GEOMETRIQUE_ET_MAILLAGES, CODE_INFORMATIQUE_QUANTIQUE, CODE_INTEGRATION_DES_DONNEES, CODE_GENIE_LOGICIEL_AVANCE, CODE_FIABILITE_LOGICIELLE, CODE_EXPLORATION_DES_DONNEES, CODE_DES_CONTENEURS_AU_CLOUD, CODE_CALCULABILITE_AVANCEE, CODE_ANALYSE_DE_PROGRAMMES, CODE_ALGORITHMES_ET_SYSTEMES_ROBUSTES, CODE_ALGORITHMES_A_PERFORMANCES_GARANTIES, CODE_ARCHITECTURES_JEE, CODE_ANALYSE_DES_DONNEES, CODE_SECURITE_DES_APPS, CODE_DONNEES_POST_RELATIONNELLES, CODE_PROG_CPP, CODE_BDD_AVANCE, CODE_CRYPTOGRAPHIE},
	"FSI": {CODE_REU_GIG, CODE_THEORIE_DE_LA_COMPLEXITE, CODE_THEORIE_STRUCTURELLE_DES_GRAPHES, CODE_RESEAUX_DE_NEURONES, CODE_TRAITEMENT_AUTOMATIQUE_DES_LANGUES, CODE_MODELISATION_ET_RESOLUTION_POUR_LA_DECISION, CODE_PROGRAMMATION_GRAPHIQUE, CODE_SURFACES_DE_FORME_LIBRE, CODE_INTERFACE_HUMAIN_MACHINE, CODE_MODELISATION_GEOMETRIQUE_ET_MAILLAGES, CODE_INFORMATIQUE_QUANTIQUE, CODE_INTEGRATION_DES_DONNEES, CODE_GENIE_LOGICIEL_AVANCE, CODE_EXPLORATION_DES_DONNEES, CODE_CALCULABILITE_AVANCEE, CODE_BASES_DE_APPRENTISSAGE_ARTIFICIEL, CODE_ALGORITHMES_A_PERFORMANCES_GARANTIES, CODE_ARCHITECTURES_JEE, CODE_ANALYSE_DES_DONNEES, CODE_PROBA_POUR_INFORMATIQUE, CODE_PROG_FONCTIONNELLE, CODE_METHODE_NUM_INFORMATIQUE, CODE_DONNEES_POST_RELATIONNELLES, CODE_PROG_CPP, CODE_BDD_AVANCE},
	"GIG": {CODE_THEORIE_DE_LA_COMPLEXITE, CODE_THEORIE_STRUCTURELLE_DES_GRAPHES, CODE_RESEAUX_DE_NEURONES, CODE_TRAITEMENT_AUTOMATIQUE_DES_LANGUES, CODE_MODELISATION_ET_RESOLUTION_POUR_LA_DECISION, CODE_INTEGRATION_DES_DONNEES, CODE_INFORMATIQUE_QUANTIQUE, CODE_GENIE_LOGICIEL_AVANCE, CODE_FIABILITE_LOGICIELLE, CODE_EXPLORATION_DES_DONNEES, CODE_DES_CONTENEURS_AU_CLOUD, CODE_CALCULABILITE_AVANCEE, CODE_BASES_DE_APPRENTISSAGE_ARTIFICIEL, CODE_ANALYSE_DE_PROGRAMMES, CODE_ALGORITHMES_ET_SYSTEMES_ROBUSTES, CODE_ALGORITHMES_A_PERFORMANCES_GARANTIES, CODE_ARCHITECTURES_JEE, CODE_ANALYSE_DES_DONNEES, CODE_SECURITE_DES_APPS, CODE_PROBA_POUR_INFORMATIQUE, CODE_PROG_FONCTIONNELLE, CODE_DONNEES_POST_RELATIONNELLES, CODE_BDD_AVANCE, CODE_CRYPTOGRAPHIE},
	"IMD": {CODE_REU_GIG, CODE_RESEAUX_DE_NEURONES, CODE_TRAITEMENT_AUTOMATIQUE_DES_LANGUES, CODE_MODELISATION_ET_RESOLUTION_POUR_LA_DECISION, CODE_PROGRAMMATION_GRAPHIQUE, CODE_SURFACES_DE_FORME_LIBRE, CODE_INTERFACE_HUMAIN_MACHINE, CODE_MODELISATION_GEOMETRIQUE_ET_MAILLAGES, CODE_INFORMATIQUE_QUANTIQUE, CODE_INTEGRATION_DES_DONNEES, CODE_GENIE_LOGICIEL_AVANCE, CODE_FIABILITE_LOGICIELLE, CODE_EXPLORATION_DES_DONNEES, CODE_DES_CONTENEURS_AU_CLOUD, CODE_BASES_DE_APPRENTISSAGE_ARTIFICIEL, CODE_ANALYSE_DE_PROGRAMMES, CODE_ALGORITHMES_ET_SYSTEMES_ROBUSTES, CODE_ARCHITECTURES_JEE, CODE_ANALYSE_DES_DONNEES, CODE_SECURITE_DES_APPS, CODE_PROG_FONCTIONNELLE, CODE_SDD_AA, CODE_DONNEES_POST_RELATIONNELLES, CODE_PROG_CPP, CODE_BDD_AVANCE, CODE_CRYPTOGRAPHIE},
	"SID": {CODE_REU_GIG, CODE_THEORIE_DE_LA_COMPLEXITE, CODE_THEORIE_STRUCTURELLE_DES_GRAPHES, CODE_RESEAUX_DE_NEURONES, CODE_MODELISATION_ET_RESOLUTION_POUR_LA_DECISION, CODE_PROGRAMMATION_GRAPHIQUE, CODE_SURFACES_DE_FORME_LIBRE, CODE_INTERFACE_HUMAIN_MACHINE, CODE_MODELISATION_GEOMETRIQUE_ET_MAILLAGES, CODE_INFORMATIQUE_QUANTIQUE, CODE_GENIE_LOGICIEL_AVANCE, CODE_FIABILITE_LOGICIELLE, CODE_DES_CONTENEURS_AU_CLOUD, CODE_CALCULABILITE_AVANCEE, CODE_BASES_DE_APPRENTISSAGE_ARTIFICIEL, CODE_ANALYSE_DE_PROGRAMMES, CODE_ALGORITHMES_ET_SYSTEMES_ROBUSTES, CODE_ALGORITHMES_A_PERFORMANCES_GARANTIES, CODE_ARCHITECTURES_JEE, CODE_SECURITE_DES_APPS, CODE_PROBA_POUR_INFORMATIQUE, CODE_PROG_FONCTIONNELLE, CODE_METHODE_NUM_INFORMATIQUE, CODE_PROG_CPP, CODE_CRYPTOGRAPHIE},
}

// Transcript group numbers to regex expressions
var groupToRegexMap = map[Group]string{
	"TD1":  " TD1| TD Gr1|TD 1| TD - Gr1| COM 1",
	"TD2":  " TD2| TD Gr2|TD 2| COM 2",
	"TD3":  " TD3| TD Gr3|TP 3| COM 3",
	"TD4":  " TD4| TD Gr4|TD 4| COM 4",
	"TP1":  " TP1| TP Gr1|TP 1",
	"TP2":  " TP2| TP Gr2|TP 2",
	"TP3":  " TP3| TP Gr3|TP 3",
	"TP4":  " TP4| TP Gr4|TP 4",
	"ANG1": "Anglais de l'informatique Grp 1",
	"ANG2": "Anglais de l'informatique Grp 2",
	"ANG3": "Anglais de l'informatique Grp 3",
	"ANG4": "Anglais de l'informatique Grp 4",
	"ANG5": "Anglais de l'informatique Grp 5",
}

// Transcript option group numbers to regex expressions
var optionGroupNumberToRegexMap = map[string]string{
	"A1":     " Gr A1",
	"A2":     " Gr A2",
	"A3":     " Gr A3",
	"C1":     " Gr C1",
	"C2":     " Gr C2",
	"F1":     " F1",
	"F2":     " F2",
	"H1":     " H1",
	"H2":     " H2",
	"E1":     " E1",
	"E2":     " E2",
	"D1":     " D1",
	"D2":     " D2",
	"G1":     " G1",
	"G2":     " G2",
	"FL1":    " Fiabilité logicielle Gpr 1",
	"FL2":    " Fiabilité logicielle Gpr 2",
	"GL1":    "GRP 1 " + CODE_GENIE_LOGICIEL_AVANCE,
	"GL2":    "GRP 2 " + CODE_GENIE_LOGICIEL_AVANCE,
	"TAA1":   " Traitement automatique des langues Grp 1",
	"TAA2":   " Traitement automatique des langues Grp 2",
	"CLOUD1": " principes et administration Grp 1",
	"CLOUD2": " principes et administration Grp 2",
}
